### ISSUE TITLE
Several `panick`s when trying to run tests

### ISSUE THREAD

**Issue by gjtorikian** [trishume/syntect#23]
I'm on macOS 10.12.1, rustc 1.13.0, and a fresh `cargo test` reports the following failures.

```
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/syntect-a38ef98faf98fd4c

running 20 tests
test highlighting::selector::tests::matching_works ... ok
test highlighting::selector::tests::selectors_work ... ok
test dumps::tests::can_dump_and_load ... FAILED
test highlighting::highlighter::tests::can_parse ... FAILED
test html::tests::tricky_test_syntax ... FAILED
test parsing::scope::tests::global_repo_works ... ok
test parsing::scope::tests::matching_works ... ok
test parsing::scope::tests::misc ... ok
test parsing::parser::tests::can_parse ... FAILED
test parsing::scope::tests::prefixes_work ... ok
test parsing::scope::tests::repo_works ... ok
test parsing::syntax_definition::tests::can_compile_refs ... ok
test parsing::yaml_load::tests::can_parse ... ok
test parsing::syntax_set::tests::can_load ... FAILED
test highlighting::theme_set::tests::can_parse_common_themes ... ok
test easy::tests::can_find_regions ... ok
test easy::tests::can_highlight_file ... ok
test easy::tests::can_highlight_lines ... ok
test html::tests::tokens ... ok
test html::tests::strings ... ok

failures:

---- dumps::tests::can_dump_and_load stdout ----
	thread 'dumps::tests::can_dump_and_load' panicked at 'called `Result::unwrap()` on an `Err` value: ParseSyntax(MissingMandatoryKey("match"))', ../src/libcore/result.rs:799
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- highlighting::highlighter::tests::can_parse stdout ----
	thread 'highlighting::highlighter::tests::can_parse' panicked at 'called `Result::unwrap()` on an `Err` value: ParseSyntax(MissingMandatoryKey("match"))', ../src/libcore/result.rs:799

---- html::tests::tricky_test_syntax stdout ----
	thread 'html::tests::tricky_test_syntax' panicked at 'called `Result::unwrap()` on an `Err` value: ParseSyntax(MissingMandatoryKey("match"))', ../src/libcore/result.rs:799

---- parsing::parser::tests::can_parse stdout ----
	thread 'parsing::parser::tests::can_parse' panicked at 'called `Result::unwrap()` on an `Err` value: ParseSyntax(MissingMandatoryKey("match"))', ../src/libcore/result.rs:799

---- parsing::syntax_set::tests::can_load stdout ----
	thread 'parsing::syntax_set::tests::can_load' panicked at 'called `Result::unwrap()` on an `Err` value: ParseSyntax(MissingMandatoryKey("match"))', ../src/libcore/result.rs:799


failures:
    dumps::tests::can_dump_and_load
    highlighting::highlighter::tests::can_parse
    html::tests::tricky_test_syntax
    parsing::parser::tests::can_parse
    parsing::syntax_set::tests::can_load

test result: FAILED. 15 passed; 5 failed; 0 ignored; 0 measured

error: test failed
```

Any thoughts? Can I provide more information or help out in some way?

**Comment by gjtorikian** [comment]
This is my first "real" Rust project I'm trying to contribute to, so apologies if these are all newb concerns. 

After some Googling I discovered that the `unwrap()`, which is called throughout the tests, doesn't take into account if the operation errored. How would you feel if I made PR changes similar to the following?

``` diff
diff --git a/src/highlighting/highlighter.rs b/src/highlighting/highlighter.rs
index dd4713b..bf47ec9 100644
--- a/src/highlighting/highlighter.rs
+++ b/src/highlighting/highlighter.rs
@@ -245,7 +245,10 @@ mod tests {
 
     #[test]
     fn can_parse() {
-        let ps = SyntaxSet::load_from_folder("testdata/Packages").unwrap();
+        let ps = match SyntaxSet::load_from_folder("testdata/Packages") {
+            Ok(val) => val,
+            Err(err) => panic!("called `Result::unwrap()` on an `Err` value: {:?}", err),
+        };
         let mut state = {
             let syntax = ps.find_syntax_by_name("Ruby on Rails").unwrap();
             ParseState::new(syntax)
```

I'm still searching for the root cause. The result of that change is:

```
---- highlighting::highlighter::tests::can_parse stdout ----
	thread 'highlighting::highlighter::tests::can_parse' panicked at 'called `Result::unwrap()` on an `Err` value: ParseSyntax(MissingMandatoryKey("match"))', src/highlighting/highlighter.rs:250
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

My current theory is that the Git SHA I have for `testdata/Packages` (`4db940a`) is incompatible with the one you're at (`d228c5c5e56bdf6056afb131a2e5df43e8810281`).

**Comment by gjtorikian** [comment]
> My current theory is that the Git SHA I have for testdata/Packages (4db940a) is incompatible with the one you're at (d228c5c5e56bdf6056afb131a2e5df43e8810281).

Yup, that was exactly it.

I leave it to you if you want me to go and fix the `unwrap`s or not. When I cloned this project I had lazily ran

```
git submodule foreach git pull origin master
```

instead of

```
git submodule update --init
```

Could be a documentation fix too.

**Comment by trishume** [comment]
Yah there were one or two new features added to the Sublime Text packages repo that I don't support yet. Hence, errors when my parser tries to parse constructs it doesn't recognize.

Please don't replace the unwraps, they are doing exactly what they are supposed to do. The code you propose replacing them with does exactly the same thing as unwrap does except with way more code.

Really the problem is that I don't support those features. One of them is the [`clear_scopes`](https://www.sublimetext.com/docs/3/syntax.html) option, but they may have added more.

**Comment by gjtorikian** [comment]
Ok. 👌🏽Can I make a documentation change to the README to list how to fetch the submodules? I always forget and basically googled the wrong answer.

**Comment by trishume** [comment]
Sure if you want.
