### ISSUE TITLE
Problem loading sublime-color-scheme files

### ISSUE THREAD

**Issue by brupelo** [trishume/syntect#244]
I was trying to use the official [Monokai.sublime-color-scheme](https://raw.githubusercontent.com/twolfson/sublime-files/master/Packages/Color%20Scheme%20-%20Default/Monokai.sublime-color-scheme) with syntect but it seems this file-format is not supported or maybe it's just me doing something fishy.

I've tried to load it both as json or as xml (ie: used this converter [https://www.freeformatter.com/json-to-xml-converter.html](https://www.freeformatter.com/json-to-xml-converter.html)) but when feeding it with `ThemeSet::get_theme` it will crash.

On the other hand, if using a proper thTheme such as [monokai.tmTheme](https://github.com/richrd/suplemon/blob/master/suplemon/themes/monokai.tmTheme) there won't be any problem.

**Comment by trishume** [comment]
Yah the new color scheme format is different and not supported yet and possibly ever

**Comment by brupelo** [comment]
Just for the record... my previous thumbdown icon is mainly because your "possibly ever" end of statement, why do you think this one is not interesting but supporting old verbose meaty xml files that should be burn in hell is better?

You know, I know and everybody knows... but here's some random link google gave me after searching "json vs xml" -> [https://blog.cloud-elements.com/json-better-xml](https://blog.cloud-elements.com/json-better-xml).

As for json vs yaml I don't have any strong opinnion though, here's some random link [https://www.json2yaml.com/yaml-vs-json](https://www.json2yaml.com/yaml-vs-json)

**Comment by trishume** [comment]
Mostly because I only do open source for fun and out of generosity, and supporting the new theme format is so far down my todo list that I'll never do it myself. I'd be happy to accept a PR to implement it, but I don't think anyone really needs it since nearly all themes are available as tmThemes and I think the new format is reasonably complex, so I don't expect anybody else to contribute it.

**Comment by brupelo** [comment]
I understand, makes total sense, thanks to let me know :) . Kind of related... today I was wondering about something related... I asked in the math stackexchange site something I'm not sure about, ie: [can-be-an-open-source-project-considered-a-cooperative-game](https://math.stackexchange.com/questions/3151787/can-be-an-open-source-project-considered-a-cooperative-game), probably it won't receive any answer but it's intriguing me.

Anyway, I do think the first requirement for a project to become cool&successful is the author/contributors/teams having **fun** so it makes total sense what you're saying there, my thumbdown is not valid anymore lol.

On a serious note, the reason why I've opened this issue was mainly cos last night I was testing some monokai xml file I've found on the internet and I've noticed the outcome wasn't exactly the same than my dear Sublime's monokai, take a look here:

![showcase](https://dl.dropboxusercontent.com/s/qmq1yoc4gtecwhy/chrome_2019-03-17_19-23-23.png)

So my first thought was using directly sublime's so I don't need to even learn how to tweak these thThemes mysefl... Too many years using monokai so these subtle differences disturb me :)

**Comment by brupelo** [comment]
> As of Sublime Text 3 build 3149, a new color scheme format .sublime-color-scheme was introduced for easier editing, customization and addition of new features. The documentation for the new format is available at the main Color Schemes documentation.
> 
> This page documents Sublime Text's implementation of the legacy .tmTheme format. Support for this legacy format will remain for backwards compatibility, but new features will only be added to the .sublime-color-scheme format.

I'm sure you were already aware of these [docs](https://www.sublimetext.com/docs/3/color_schemes_tmtheme.html)... but it's quite interesting, specially the part which says `new features will only be added to the .sublime-color-scheme format.` :(

**Comment by ntwb** [comment]
FYI: I just installed [this Sublime plugin](https://github.com/dhelonious/SublimeColorSchemeConverter) and opened up a relatively new `theme.sublime-color-scheme format` file and CTRL+SHIFT+P to run the `SublimeColorSchemeConverter: Convert to tmTheme` command to which I ended up with what appears to be a pretty good XML formatted `theme.tmTheme` file.

I'm hoping, anything that is a _new feature_ from the source file will simply be _ignored_ by syntect and, fingers crossed, it not throw any errors.

I'll use this tmTheme with https://github.com/sharkdp/bat for a few days to see how it goes 🎉

**Comment by jrappen** [comment]
Relevant Sublime Text docs here:

https://www.sublimetext.com/docs/color_schemes.html

Currently undocumented:

* font_style: `glow` for ST4051+ (API `view.style_for_scope()` ST4063+)

There are a few Sublime Text color scheme features **only** supported by `*.sublime-color-scheme` (and/or `*.hidden-color-scheme`) files. Unfortunately I do not have a list of differences. I assume starting with the **changelog** section on the docs page linked above would be a start.

---

Also I only saw support for hidden syntax files, not hidden color scheme files here. Compare the following file extensions:

```bash
# TextMate format

*.tmTheme
*.hidden-tmTheme


# Sublime Text format

*.sublime-color-scheme
*.hidden-color-scheme
```

**Comment by eproxus** [comment]
Tried the method suggested by @ntwb and it seems the plugin doesn't work for modern `.sublime-color-scheme` files anymore.  Since more and more Sublime themes are migrated or created in this format, the `.tmTheme` format feels more dead by the day.

Would love for `syntect` to support this new format!

**Comment by keith-hall** [comment]
out of curiosity, what color schemes have you found that can't be converted using that plugin, and what error was shown in the ST console? I noticed it for some reason currently has some unnecessary limitations like not supporting comments in the json color schemes (rather than just ignoring them, if it's too tricky to output in the tmTheme).

**Comment by eproxus** [comment]
@keith-hall Could be because of Sublime Text 4 and Python 3 though (build 4074). I'm getting this when converting a [Gruvbox theme](https://github.com/Briles/gruvbox/blob/master/gruvbox%20(Dark)%20(Hard).sublime-color-scheme):
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1314, in run_
    return self.run(edit)
  File "/Users/alind/Library/Application Support/Sublime Text/Installed Packages/SublimeColorSchemeConverter.sublime-package/sublime_color_scheme_converter.py", line 221, in run
  File "/Users/alind/Library/Application Support/Sublime Text/Installed Packages/SublimeColorSchemeConverter.sublime-package/sublime_color_scheme_converter.py", line 155, in parse
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by keith-hall** [comment]
I had a play around with it, and this works for me with that color scheme:

```py
"""
SublimeColorSchemeConverter

Converts sublime-color-scheme json files into tmTheme plist files.
"""

import os
import re
import json
#import plistlib
import colorsys
import traceback
import collections

import sublime
import sublime_plugin

from .lib import plistlib

re_var = re.compile(r"var\([^\)]+\)")
re_alpha = re.compile(r"alpha\(((0\.)?[0-9]+)\)")
re_hex = re.compile(r"(#[0-9,a-z,A-Z]{6})([0-9,a-z,A-Z]{2})?")
re_rgb = re.compile(r"rgb\((\d+),\s?(\d+),\s?(\d+)(,\s?(\d+\.?\d*))?\)")
re_hsl = re.compile(r"hsl\((\d+),\s?(\d+)%,\s?(\d+)%(,\s?(\d+\.?\d*))?\)")

def alpha_to_hex(a):
    return "{:02x}".format(int(255*float(a)))

def hexa_to_hex(hex, a):
    return hex[:7] + alpha_to_hex(a)

def rgb_to_hex(r, g, b, a=None):
    hexcode = "#{:02x}{:02x}{:02x}".format(r, g, b)
    if a:
        hexcode += alpha_to_hex(a)
    return hexcode

def get_alpha_adjuster(string, default=None):
    alpha = re_alpha.search(string)
    if alpha:
        return float(alpha.group(1))
    else:
        return default

def get_alpha_hex(hexcode):
    if len(hexcode) < 8:
        return None
    else:
        return int(hexcode[7:], 16)

def match_hex(string):
    result = None
    match = re_hex.search(string)
    if match:
        result = match.group(1)
        alpha = get_alpha_adjuster(string)
        if alpha:
            result += alpha_to_hex(alpha)
        elif match.group(2):
            result += match.group(2)
    return result

def match_rgb(string):
    match = re_rgb.search(string)
    result = None
    if match:
        r = int(match.group(1))
        g = int(match.group(2))
        b = int(match.group(3))
        a = get_alpha_adjuster(string, match.group(5))
        result = rgb_to_hex(r, g, b, a)
    return result

def match_hsl(string):
    match = re_hsl.search(string)
    result = None
    if match:
        h = int(match.group(1))/360
        s = int(match.group(2))/100
        l = int(match.group(3))/100
        a = get_alpha_adjuster(string, match.group(5))
        r, g, b = [255*int(v) for v in colorsys.hls_to_rgb(h, l, s)]
        result = rgb_to_hex(r, g, b, a)
    return result

def try_match_color(string):
    hexcode = match_hex(string)
    if not hexcode:
        hexcode = match_rgb(string)
    if not hexcode:
        hexcode = match_hsl(string)
    if hexcode:
        alpha = get_alpha_adjuster(string, None)
        if alpha:
            hexcode = hexa_to_hex(hexcode[:7], alpha)
    else:
        hexcode = string
    return hexcode

class ConvertSublimeColorSchemeCommand(sublime_plugin.TextCommand):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.filename = None
        self.theme = None
        self.output = None
        self.output_view = None

    def convert_name(self, string):
        return re.sub(
            "_([a-z,A-Z,0-9])",
            lambda match: match.group(1).upper(),
            string
        )

    def parse_color(self, key, variables):
        if key in variables.keys():
            print(variables[key], key, try_match_color(variables[key]))
            return try_match_color(variables[key])
        else:
            var = re_var.search(key)
            if var:
                color = variables.get(var.group(), var.group())
                return try_match_color(key.replace(var.group(), color))
            else:
                return try_match_color(key)

    def parse_settings(self, settings, variables):
        parsed = {}
        for key in list(settings):
            value = settings[key]
            parsed[self.convert_name(key)] = self.parse_color(value, variables)
        return parsed

    def parse_rules(self, rules, variables):
        parsed = []
        for settings in rules:
            rule = {}
            name = settings.pop("name", None)
            if name:
                rule["name"] = name
            scope = settings.pop("scope", None)
            if scope:
                rule["scope"] = scope
            rule["settings"] = self.parse_settings(settings, variables)
            parsed.append(rule)
        return parsed

    def parse(self):
        name = self.theme.get("name", None)
        author = self.theme.get("author", None)
        variables = self.theme.get("variables", None)
        globals_ = self.theme["globals"]
        rules = self.theme["rules"]

        for key in list(variables):
            variables["var({})".format(key)] = variables.pop(key)

        # handle nested variables
        for key in variables.keys():
            variables[key] = self.parse_color(variables[key], variables)

        settings = self.parse_settings(globals_, variables)
        rules = self.parse_rules(rules, variables)
        self.theme = {
            "name": name,
            "author": author,
            "settings": [{"settings": settings}] + rules
        }

    def convert(self):
        error = False
        try:
            plistbytes = plistlib.dumps(self.theme, sort_keys=False)
            self.output = plistbytes.decode('UTF-8')
        except Exception:
            error = True
            sublime.error_message("Could not convert Sublime Color Scheme")
            print("SublimeColorSchemeConverter:")
            print(traceback.format_exc())
        return error

    def read_source(self):
        self.theme = sublime.decode_value(self.view.substr(sublime.Region(0, self.view.size())))
        return False

    def write_buffer(self, edit):
        error = False
        #output_name = os.path.splitext(os.path.basename(self.filename))[0] \
        #              + ".tmTheme"
        try:
            self.output_view = self.view.window().new_file()
            self.output_view.set_encoding("UTF-8")
            #self.output_view.set_name(output_name)
            self.output_view.replace(
                edit,
                sublime.Region(0, self.view.size()),
                self.output
            )
            self.output = None
        except Exception:
            error = True
            sublime.error_message("Could not write buffer")
            print("SublimeColorSchemeConverter:")
            print(traceback.format_exc())
        return error

    def run(self, edit):
        if not self.read_source():
            if not self.parse():
                if not self.convert():
                    self.write_buffer(edit)
        self.filename = None
        self.theme = None
        self.output = None
```

I'm not convinced it correctly calculates nested alpha modifiers though...

**Comment by eproxus** [comment]
@keith-hall I think this is mentioned in the README:
> The plugin tries to replace all patterns, where any color is recognized. Therefore color(#000000 blend(#ffffff 50%)) is replaced by #000000, since the blend() adjuster syntax is not supported.

**Comment by philpax** [comment]
Hi all,

I ran into this when trying to use Ayu Dark (which is no longer distributed as a `tmTheme`) and decided I'd cobble together an implementation (built on top of `serde`, `serde_json`, `syntect 5.2`, and `thiserror`):

```rust
use std::{collections::HashMap, str::FromStr};

use serde::Deserialize;
use syntect::{
    highlighting::{
        Color, FontStyle, ParseThemeError, ScopeSelectors, StyleModifier, Theme, ThemeItem,
        ThemeSettings, UnderlineOption,
    },
    parsing::ParseScopeError,
};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum ParseError {
    #[error("Failed to parse JSON")]
    Json(#[from] serde_json::Error),
    #[error("Failed to parse scope")]
    ParseScope(#[from] ParseScopeError),
    #[error("Failed to parse theme")]
    ParseTheme(#[from] ParseThemeError),
}

#[derive(Deserialize)]
pub struct ColorScheme {
    pub name: Option<String>,
    pub author: Option<String>,
    pub globals: HashMap<String, String>,
    pub rules: Vec<Rule>,
}
impl FromStr for ColorScheme {
    type Err = ParseError;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        serde_json::from_str(s).map_err(ParseError::Json)
    }
}
impl TryFrom<ColorScheme> for Theme {
    type Error = ParseError;
    fn try_from(value: ColorScheme) -> Result<Self, Self::Error> {
        let mut settings = ThemeSettings::default();
        for (key, value) in &value.globals {
            match &key[..] {
                "foreground" => settings.foreground = Color::from_str(value).ok(),
                "background" => settings.background = Color::from_str(value).ok(),
                "caret" => settings.caret = Color::from_str(value).ok(),
                "line_highlight" => settings.line_highlight = Color::from_str(value).ok(),
                "misspelling" => settings.misspelling = Color::from_str(value).ok(),
                "minimap_border" => settings.minimap_border = Color::from_str(value).ok(),
                "accent" => settings.accent = Color::from_str(value).ok(),

                "popup_css" => settings.popup_css = Some(value.clone()),
                "phantom_css" => settings.phantom_css = Some(value.clone()),

                "bracket_contents_foreground" => {
                    settings.bracket_contents_foreground = Color::from_str(value).ok()
                }
                "bracket_contents_options" => {
                    settings.bracket_contents_options = UnderlineOption::from_str(value).ok()
                }
                "brackets_foreground" => settings.brackets_foreground = Color::from_str(value).ok(),
                "brackets_background" => settings.brackets_background = Color::from_str(value).ok(),
                "brackets_options" => {
                    settings.brackets_options = UnderlineOption::from_str(value).ok()
                }
                "tags_foreground" => settings.tags_foreground = Color::from_str(value).ok(),
                "tags_options" => settings.tags_options = UnderlineOption::from_str(value).ok(),
                "highlight" => settings.highlight = Color::from_str(value).ok(),
                "find_highlight" => settings.find_highlight = Color::from_str(value).ok(),
                "find_highlight_foreground" => {
                    settings.find_highlight_foreground = Color::from_str(value).ok()
                }
                "gutter" => settings.gutter = Color::from_str(value).ok(),
                "gutter_foreground" => settings.gutter_foreground = Color::from_str(value).ok(),
                "selection" => settings.selection = Color::from_str(value).ok(),
                "selection_foreground" => {
                    settings.selection_foreground = Color::from_str(value).ok()
                }
                "selection_border" => settings.selection_border = Color::from_str(value).ok(),
                "inactive_selection" => settings.inactive_selection = Color::from_str(value).ok(),
                "inactive_selection_foreground" => {
                    settings.inactive_selection_foreground = Color::from_str(value).ok()
                }
                "guide" => settings.guide = Color::from_str(value).ok(),
                "active_guide" => settings.active_guide = Color::from_str(value).ok(),
                "stack_guide" => settings.stack_guide = Color::from_str(value).ok(),
                "shadow" => settings.shadow = Color::from_str(value).ok(),
                _ => (), // E.g. "shadowWidth" and "invisibles" are ignored
            }
        }

        Ok(Self {
            name: value.name,
            author: value.author,
            settings,
            scopes: value
                .rules
                .into_iter()
                .map(ThemeItem::try_from)
                .collect::<Result<Vec<_>, _>>()?,
        })
    }
}

#[derive(Deserialize)]
pub struct Rule {
    pub name: Option<String>,
    pub scope: String,
    pub font_style: Option<String>,
    pub foreground: Option<String>,
    pub background: Option<String>,
}
impl TryFrom<Rule> for ThemeItem {
    type Error = ParseError;
    fn try_from(value: Rule) -> Result<Self, Self::Error> {
        Ok(Self {
            scope: ScopeSelectors::from_str(&value.scope)?,
            style: StyleModifier {
                foreground: value.foreground.map(|s| Color::from_str(&s)).transpose()?,
                background: value.background.map(|s| Color::from_str(&s)).transpose()?,
                font_style: value
                    .font_style
                    .map(|s| FontStyle::from_str(&s))
                    .transpose()?,
            },
        })
    }
}
```

From my brief testing, this seems to work as expected. It might not handle all of the cases - it was a fairly mechanical translation - but it should get you going. Here's an example of how to use it:
```rust
let mut set = ThemeSet::load_defaults();
let ayu_dark =
    sublime_color_scheme::ColorScheme::from_str(include_str!("ayu-dark.sublime-color-scheme"))?;
set.themes.insert("ayu-dark".to_string(), ayu_dark.try_into()?);
```

Hope this helps unblock someone! 🙂 

(I'd make a PR, but I'm not sure what test data I'd have to supply and such. I leave that up to the maintainers and anyone else interested.)

**Comment by Lepidopteran** [comment]
Hello everyone,

After getting into this issue myself with one of my projects, I made a solution that supports most features specified in the Sublime Color Scheme [Docs](https://www.sublimetext.com/docs/color_schemes.html).

It's built with `serde`, `serde_json`, `syntect`, `thiserror`, `jsonc_parser`, and `palette`. 

I've tested it on themes like `Monokai`, `Nord`, `Gruvbox Material`, `Catppuccin`, and `Kanagawa`, and I'm happy to say they all work as far as I can tell.

I'd like to also thank @philpax for supplying the original code that kick started this whole thing in the place.

I would love to see this implemented in base `syntect`, but I'm happy with my solution, I'll put a link to it right [here](https://crates.io/crates/sublime-color-scheme) if anybody is interested in it.

If any are interested on how they turned out visually, I took some screenshots down below of some example code.

## Screenshots

### Kanagawa
![Image](https://github.com/user-attachments/assets/f34925bd-ea3d-4142-84ed-50c7cef9586e)

### Catppuccin
![Image](https://github.com/user-attachments/assets/b95d17f7-63b7-43c4-81e1-4e460ad6f20d)

### Nord
![Image](https://github.com/user-attachments/assets/193c8455-c9db-4612-af9d-d0ffe676d673)

### Monokai
![Image](https://github.com/user-attachments/assets/3173f010-0fbe-4fad-ae37-f67ae39b0ede)

### Gruvbox Material
![Image](https://github.com/user-attachments/assets/ec813c8d-3919-4cbb-8e51-3f57063f69a9)

**Comment by keith-hall** [comment]
Very cool, thanks for sharing @Lepidopteran ! I personally think it would make sense to have that functionality in `syntect` directly, mainly because I don't see any other way to easily add https://www.sublimetext.com/docs/color_schemes.html#hashed-syntax-highlighting support...

**Comment by Lepidopteran** [comment]
Thank you for the complement @keith-hall ! 

It would be awesome to have the functionality upstream. 

I got _most_ of the features working from the docs, such as every color function, variables, and every color adjuster.

However I wasn't able to support [`foreground_adjust`](https://www.sublimetext.com/docs/color_schemes.html#foreground_adjust) and I don't believe [`hashed-sytax-highlighting`](https://www.sublimetext.com/docs/color_schemes.html#hashed-syntax-highlighting) is supported either unless I'm mistaken in assuming `hased-syntax-highlighting` is supplying an array of colors to the `foreground` or `background` fields, for example `"foreground": ["hsl(200, 60%, 70%)", "hsl(330, 60%, 70%)"]`.

The reason I didn't support the `foreground_adjust` field is because I'm confused of the wording from the docs. 

> The "foreground_adjust" key accepts a space-separated list of adjusters that are supported by the [minihtml Color](https://www.sublimetext.com/docs/minihtml.html#colors). It is only supported when the "background" key is also specified, and thus allows modifying all foregrounds used in combination with the background, without having to create different rules for every permutation.

My first assumption was to just adjust the `background` color using a list of adjusters, then use the adjusted background color for the foreground, but I'm not fully sure that assumption is correct as I've never wrote `sublime-color-scheme` file or even used the Sublime Text.

I would love to support it though.

I'm also not fully sure how to implement the functionality of converting the `sublime-color-scheme` to `serde` without first preprocessing it with `jsonc_parser` as `sublime-color-scheme` files seem to use [JSON with comments](https://code.visualstudio.com/docs/languages/json#_json-with-comments) syntax and `serde_json` will not support said syntax serde-rs/json#168, which is understandable as json is purely meant to be a data transfer format.

Lastly I would need to implement the functionality of `palette` such as, [named colors](https://docs.rs/palette/latest/palette/named/index.html), [color conversion](https://docs.rs/palette/latest/palette/convert/index.html) of `hsl` and `hwb` colorspaces to `srgb`, and [mixing](https://docs.rs/palette/latest/palette/trait.Mix.html) of colors.

I'd also need a way to convert `srgb` into a `linear rgb` or `hsl` to apply the modifications using parsed "color adjusters".

I'm writing all of this assuming people would prefer not adding any dependencies.

However I'm definitely willing to help, and would love to make PR.

Any additional input would be greatly appreciated!

**Comment by keith-hall** [comment]
> I'm writing all of this assuming people would prefer not adding any dependencies

I'm personally of the opinion that color spaces etc are the kind of thing that it *would* make sense to rely on a dependency for. Reinventing the wheel - when there are crates doing a good job already - seems to me like unnecessary busy work, just for she sole benefit of not pulling in any extra dependencies... Sometimes it is okay to say that we are not interested in the extra maintenance overhead of having such code directly in our codebase, needing all maintainers to understand it etc 🙂


> I don't believe [`hashed-sytax-highlighting`](https://www.sublimetext.com/docs/color_schemes.html#hashed-syntax-highlighting) is supported either unless I'm mistaken in assuming `hased-syntax-highlighting` is supplying an array of colors to the `foreground` or `background` fields, for example `"foreground": ["hsl(200, 60%, 70%)", "hsl(330, 60%, 70%)"]`.

You're not mistaken. 👍 That's kinda what I meant about why it would be useful to expand `syntect`'s support rather than rely on the current `Theme` struct which only caters for `tmTheme` functionality - which doesn't include hashed syntax highlighting.

I see one possible approach could be (perhaps under a feature) for `syntect` to have a dependency on your crate if it makes more sense, and we resolve the circular dependency problem... Not sure how others would feel about that, but it's just an idea I'm throwing out there 😉

> `foreground_adjust`

I also have no experience to draw upon here, I believe the way forward would be to experiment in ST with various tweaks to a `sublime-color-scheme`, use a color dropper and some math to do some analysis of how it works. ...or ask for clarification from the ST devs, I guess 😆

> I'm also not fully sure how to implement the functionality of converting the `sublime-color-scheme` to `serde` without first preprocessing it with `jsonc_parser`

Maybe preprocessing is an acceptable solution for now, which can be iterated on in future if we get some better ideas. As `syntect` generally works with binary dumps anyway, I don't see it as a big problem really 🙂

**Comment by Lepidopteran** [comment]
> I'm personally of the opinion that color spaces etc are the kind of thing that it would make sense to rely on a dependency for. Reinventing the wheel - when there are crates doing a good job already - seems to me like unnecessary busy work, just for she sole benefit of not pulling in any extra dependencies... Sometimes it is okay to say that we are not interested in the extra maintenance overhead of having such code directly in our codebase, needing all maintainers to understand it etc

I completely agree, the palette crate is great and I'd prefer not reinventing the wheel!

> That's kinda what I meant about why it would be useful to expand `syntect`'s support rather than rely on the current `Theme` struct which only caters for `tmTheme` functionality - which doesn't include hashed syntax highlighting.

I see, that make senses to me! 

>  use a color dropper and some math to do some analysis of how it works. ...or ask for clarification from the ST devs, I guess 😆

Will do, I definitely want to be able to support it as seems like useful feature of the "newer" spec, though I've only found a few cases where it used, like for example the Gruvbox theme:

```json 
{
    "scope": "diff.deleted",
    "background": "hsla(357, 45%, 60%, 0.15)",
    "foreground_adjust": "l(+ 5%)"
},
```

I might ask some theme authors or like you suggested, _do it myself_ or ask the ST devs.

> I see one possible approach could be (perhaps under a feature) for syntect to have a dependency on your crate if it makes more sense, and we resolve the circular dependency problem

I personally see that as a good solution as well, It would make it so developers can optionally include sublime-color-scheme support. 

However, I could also see the argument that `syntect` should have built-in support of `sublime-color-scheme` files.

I definitely would like to hear others thoughts on this.
