### ISSUE TITLE
Markdown lists fail to parse

### ISSUE THREAD

**Issue by qtfkwk** [trishume/syntect#326]
# Reproduce

## Prep

```
cargo init test
cd test
cargo add syntect # 4.5.0
```

## Works

`src/main.rs`:

```Rust
use syntect::html::{ClassStyle, ClassedHTMLGenerator};
use syntect::parsing::SyntaxSet;
use syntect::util::LinesWithEndings;

fn main() {
    let content = String::from("# alpha\n\n## bravo\n### charlie\n"); // works
    //let content = String::from("* alpha\n* bravo\n* charlie\n"); // does not work
    let ss = SyntaxSet::load_defaults_newlines();
    let syntax = ss.find_syntax_by_name("Markdown").unwrap();
    let mut h = ClassedHTMLGenerator::new_with_class_style(&syntax, &ss, ClassStyle::Spaced);
    for line in LinesWithEndings::from(&content) {
        h.parse_html_for_line_which_includes_newline(&line);
    }
    let result = h.finalize();
    println!("{}", result);
}
```

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/temp`
<span class="text html markdown"><span class="meta block-level markdown"><span class="markup heading 1 markdown"><span class="punctuation definition heading begin markdown">#</span> </span><span class="markup heading 1 markdown"><span class="entity name section markdown">alpha</span><span class="meta whitespace newline markdown">
</span></span></span>
<span class="meta block-level markdown"><span class="markup heading 2 markdown"><span class="punctuation definition heading begin markdown">##</span> </span><span class="markup heading 2 markdown"><span class="entity name section markdown">bravo</span><span class="meta whitespace newline markdown">
</span></span></span><span class="meta block-level markdown"><span class="markup heading markdown"><span class="punctuation definition heading begin markdown">###</span> </span><span class="markup heading markdown"><span class="entity name section markdown">charlie</span><span class="meta whitespace newline markdown">
</span></span></span></span>
```

## Breaks

`src/main.rs`:

```Rust
use syntect::html::{ClassStyle, ClassedHTMLGenerator};
use syntect::parsing::SyntaxSet;
use syntect::util::LinesWithEndings;

fn main() {
    //let content = String::from("# alpha\n\n## bravo\n### charlie\n"); // works
    let content = String::from("* alpha\n* bravo\n* charlie\n"); // does not work
    let ss = SyntaxSet::load_defaults_newlines();
    let syntax = ss.find_syntax_by_name("Markdown").unwrap();
    let mut h = ClassedHTMLGenerator::new_with_class_style(&syntax, &ss, ClassStyle::Spaced);
    for line in LinesWithEndings::from(&content) {
        h.parse_html_for_line_which_includes_newline(&line);
    }
    let result = h.finalize();
    println!("{}", result);
}
```

```
$ cargo run
   Compiling temp v0.1.0 (/home/qtfkwk/temp)
    Finished dev [unoptimized + debuginfo] target(s) in 0.79s
     Running `target/debug/temp`
thread 'main' panicked at 'tried to restore cleared scopes, but none were cleared', /home/qtfkwk/.cargo/registry/src/github.com-1ecc6299db9ec823/syntect-4.5.0/src/parsing/scope.rs:450:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by keith-hall** [comment]
Thanks for reporting. I hope to be able to make time to investigate this over the next few days.

**Comment by keith-hall** [comment]
Note that the synhtml example works fine, it seems to be a problem specific to the classed spans.

```bash
syntect on  master [?] is 📦 v4.5.0 via 🦀 v1.49.0 
❯ cargo run --example synhtml -- test.md
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/examples/synhtml test.md`
<head><title>test.md</title><style>
        pre {
            font-size:13px;
            font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace;
        }</style></head>
<body style="background-color:#2b303b;">

<pre style="background-color:#2b303b;">
<span style="color:#bf616a;">* alpha
</span><span style="color:#bf616a;">* bravo
</span><span style="color:#bf616a;">* charlie
</span></pre>

</body>
```

After repurposing the `synhtml-css-classes` example and adding
```rs
println!("----");
use crate::util::debug_print_ops;
debug_print_ops(line, &ops);
```
to the `tokens_to_classed_spans` method in `html.rs`, we see:

```
❯ RUST_BACKTRACE=1 cargo run --example synhtml-css-classes
   Compiling syntect v4.5.0 (/home/keith/repos/syntect)
    Finished dev [unoptimized + debuginfo] target(s) in 2.04s
     Running `target/debug/examples/synhtml-css-classes`
----
* alpha
^ +text.html.markdown
* alpha
^ +markup.list.unnumbered.bullet.markdown
* alpha
^ +punctuation.definition.list_item.markdown
* alpha
 ^ pop 2
* alpha
 ^ +markup.list.unnumbered.markdown
* alpha
  ^ +meta.paragraph.list.markdown
----
* bravo
^ pop 1
* bravo
^ clear TopN(1)
* bravo
^ +markup.list.unnumbered.bullet.markdown
* bravo
^ +punctuation.definition.list_item.markdown
* bravo
 ^ pop 2
* bravo
 ^ +markup.list.unnumbered.markdown
* bravo
 ^ +meta.paragraph.list.markdown
*** clear stack at clear: [[]]
----
* charlie
^ pop 2
* charlie
^ restore
* charlie
^ clear TopN(1)
* charlie
^ +markup.list.unnumbered.bullet.markdown
* charlie
^ +punctuation.definition.list_item.markdown
* charlie
 ^ pop 2
* charlie
 ^ +markup.list.unnumbered.markdown
* charlie
 ^ +meta.paragraph.list.markdown
*** clear stack at restore: []
thread 'main' panicked at 'tried to restore cleared scopes, but none were cleared', src/parsing/scope.rs:452:29
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:521:12
   1: syntect::parsing::scope::ScopeStack::apply_with_hook
             at ./src/parsing/scope.rs:452:29
   2: syntect::html::tokens_to_classed_spans
             at ./src/html.rs:324:9
   3: syntect::html::ClassedHTMLGenerator::parse_html_for_line_which_includes_newline
             at ./src/html.rs:81:39
   4: synhtml_css_classes::main
             at ./examples/synhtml-css-classes.rs:44:9
   5: core::ops::function::FnOnce::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

If we look at the sequence, it seems fine - `restore` is always preceded by a `clear`. The problem is that [`tokens_to_classed_spans` currently always creates a new scope stack for each line](https://github.com/trishume/syntect/blob/0339d1ece33abb25b13887e07fd29bb7eec8bbc5/src/html.rs#L309). But, in this scenario, we see the scope operations from the parser clear the scopes on one line and restore them on another, so this approach doesn't work.

I think we'll need to store the `ScopeStack` on the `ClassedHTMLGenerator` and update the `tokens_to_classed_spans` API to require it to be passed as a parameter instead of constructing a new one each time.
